// Mocks generated by Mockito 5.4.4 from annotations
// in time_walker/test/unit/presentation/providers/content_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:time_walker/domain/entities/encyclopedia_entry.dart' as _i4;
import 'package:time_walker/domain/entities/quiz.dart' as _i6;
import 'package:time_walker/domain/entities/quiz_category.dart' as _i7;
import 'package:time_walker/domain/entities/shop_item.dart' as _i9;
import 'package:time_walker/domain/repositories/encyclopedia_repository.dart'
    as _i2;
import 'package:time_walker/domain/repositories/quiz_repository.dart' as _i5;
import 'package:time_walker/domain/repositories/shop_repository.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EncyclopediaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncyclopediaRepository extends _i1.Mock
    implements _i2.EncyclopediaRepository {
  @override
  _i3.Future<List<_i4.EncyclopediaEntry>> getAllEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEntries,
          [],
        ),
        returnValue: _i3.Future<List<_i4.EncyclopediaEntry>>.value(
            <_i4.EncyclopediaEntry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.EncyclopediaEntry>>.value(
                <_i4.EncyclopediaEntry>[]),
      ) as _i3.Future<List<_i4.EncyclopediaEntry>>);

  @override
  _i3.Future<List<_i4.EncyclopediaEntry>> getEntriesByType(
          _i4.EntryType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i4.EncyclopediaEntry>>.value(
            <_i4.EncyclopediaEntry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.EncyclopediaEntry>>.value(
                <_i4.EncyclopediaEntry>[]),
      ) as _i3.Future<List<_i4.EncyclopediaEntry>>);

  @override
  _i3.Future<List<_i4.EncyclopediaEntry>> getEntriesByEra(String? eraId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntriesByEra,
          [eraId],
        ),
        returnValue: _i3.Future<List<_i4.EncyclopediaEntry>>.value(
            <_i4.EncyclopediaEntry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.EncyclopediaEntry>>.value(
                <_i4.EncyclopediaEntry>[]),
      ) as _i3.Future<List<_i4.EncyclopediaEntry>>);

  @override
  _i3.Future<_i4.EncyclopediaEntry?> getEntryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEntryById,
          [id],
        ),
        returnValue: _i3.Future<_i4.EncyclopediaEntry?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.EncyclopediaEntry?>.value(),
      ) as _i3.Future<_i4.EncyclopediaEntry?>);

  @override
  _i3.Future<List<_i4.EncyclopediaEntry>> searchEntries(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEntries,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.EncyclopediaEntry>>.value(
            <_i4.EncyclopediaEntry>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.EncyclopediaEntry>>.value(
                <_i4.EncyclopediaEntry>[]),
      ) as _i3.Future<List<_i4.EncyclopediaEntry>>);
}

/// A class which mocks [QuizRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizRepository extends _i1.Mock implements _i5.QuizRepository {
  @override
  _i3.Future<List<_i6.Quiz>> getAllQuizzes() => (super.noSuchMethod(
        Invocation.method(
          #getAllQuizzes,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
      ) as _i3.Future<List<_i6.Quiz>>);

  @override
  _i3.Future<List<_i6.Quiz>> getQuizzesByEra(String? eraId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuizzesByEra,
          [eraId],
        ),
        returnValue: _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
      ) as _i3.Future<List<_i6.Quiz>>);

  @override
  _i3.Future<List<_i6.Quiz>> getQuizzesByDifficulty(
          _i6.QuizDifficulty? difficulty) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuizzesByDifficulty,
          [difficulty],
        ),
        returnValue: _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
      ) as _i3.Future<List<_i6.Quiz>>);

  @override
  _i3.Future<_i6.Quiz?> getQuizById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getQuizById,
          [id],
        ),
        returnValue: _i3.Future<_i6.Quiz?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.Quiz?>.value(),
      ) as _i3.Future<_i6.Quiz?>);

  @override
  _i3.Future<List<_i7.QuizCategory>> getQuizCategories() => (super.noSuchMethod(
        Invocation.method(
          #getQuizCategories,
          [],
        ),
        returnValue:
            _i3.Future<List<_i7.QuizCategory>>.value(<_i7.QuizCategory>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.QuizCategory>>.value(<_i7.QuizCategory>[]),
      ) as _i3.Future<List<_i7.QuizCategory>>);

  @override
  _i3.Future<List<_i6.Quiz>> getQuizzesByCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuizzesByCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
      ) as _i3.Future<List<_i6.Quiz>>);

  @override
  _i3.Future<List<_i6.Quiz>> getQuizzesByDialogueId(String? dialogueId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuizzesByDialogueId,
          [dialogueId],
        ),
        returnValue: _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.Quiz>>.value(<_i6.Quiz>[]),
      ) as _i3.Future<List<_i6.Quiz>>);
}

/// A class which mocks [ShopRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopRepository extends _i1.Mock implements _i8.ShopRepository {
  @override
  _i3.Future<List<_i9.ShopItem>> getShopItems() => (super.noSuchMethod(
        Invocation.method(
          #getShopItems,
          [],
        ),
        returnValue: _i3.Future<List<_i9.ShopItem>>.value(<_i9.ShopItem>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i9.ShopItem>>.value(<_i9.ShopItem>[]),
      ) as _i3.Future<List<_i9.ShopItem>>);

  @override
  _i3.Future<List<_i9.ShopItem>> getItemsByType(_i9.ShopItemType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByType,
          [type],
        ),
        returnValue: _i3.Future<List<_i9.ShopItem>>.value(<_i9.ShopItem>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i9.ShopItem>>.value(<_i9.ShopItem>[]),
      ) as _i3.Future<List<_i9.ShopItem>>);

  @override
  _i3.Future<_i9.ShopItem?> getItemById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getItemById,
          [id],
        ),
        returnValue: _i3.Future<_i9.ShopItem?>.value(),
        returnValueForMissingStub: _i3.Future<_i9.ShopItem?>.value(),
      ) as _i3.Future<_i9.ShopItem?>);
}
