// Mocks generated by Mockito 5.4.4 from annotations
// in time_walker/test/unit/presentation/providers/exploration_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:time_walker/domain/entities/country.dart' as _i8;
import 'package:time_walker/domain/entities/era.dart' as _i6;
import 'package:time_walker/domain/entities/location.dart' as _i10;
import 'package:time_walker/domain/entities/region.dart' as _i4;
import 'package:time_walker/domain/repositories/country_repository.dart' as _i7;
import 'package:time_walker/domain/repositories/era_repository.dart' as _i5;
import 'package:time_walker/domain/repositories/location_repository.dart'
    as _i9;
import 'package:time_walker/domain/repositories/region_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RegionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegionRepository extends _i1.Mock implements _i2.RegionRepository {
  @override
  _i3.Future<List<_i4.Region>> getAllRegions() => (super.noSuchMethod(
        Invocation.method(
          #getAllRegions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Region>>.value(<_i4.Region>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Region>>.value(<_i4.Region>[]),
      ) as _i3.Future<List<_i4.Region>>);

  @override
  _i3.Future<_i4.Region?> getRegionById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getRegionById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Region?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.Region?>.value(),
      ) as _i3.Future<_i4.Region?>);

  @override
  _i3.Future<void> unlockRegion(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unlockRegion,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [EraRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEraRepository extends _i1.Mock implements _i5.EraRepository {
  @override
  _i3.Future<List<_i6.Era>> getAllEras() => (super.noSuchMethod(
        Invocation.method(
          #getAllEras,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Era>>.value(<_i6.Era>[]),
        returnValueForMissingStub: _i3.Future<List<_i6.Era>>.value(<_i6.Era>[]),
      ) as _i3.Future<List<_i6.Era>>);

  @override
  _i3.Future<List<_i6.Era>> getErasByCountry(String? countryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getErasByCountry,
          [countryId],
        ),
        returnValue: _i3.Future<List<_i6.Era>>.value(<_i6.Era>[]),
        returnValueForMissingStub: _i3.Future<List<_i6.Era>>.value(<_i6.Era>[]),
      ) as _i3.Future<List<_i6.Era>>);

  @override
  _i3.Future<_i6.Era?> getEraById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEraById,
          [id],
        ),
        returnValue: _i3.Future<_i6.Era?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.Era?>.value(),
      ) as _i3.Future<_i6.Era?>);

  @override
  _i3.Future<void> unlockEra(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unlockEra,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [CountryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryRepository extends _i1.Mock implements _i7.CountryRepository {
  @override
  _i3.Future<List<_i8.Country>> getAllCountries() => (super.noSuchMethod(
        Invocation.method(
          #getAllCountries,
          [],
        ),
        returnValue: _i3.Future<List<_i8.Country>>.value(<_i8.Country>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i8.Country>>.value(<_i8.Country>[]),
      ) as _i3.Future<List<_i8.Country>>);

  @override
  _i3.Future<List<_i8.Country>> getCountriesByRegion(String? regionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountriesByRegion,
          [regionId],
        ),
        returnValue: _i3.Future<List<_i8.Country>>.value(<_i8.Country>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i8.Country>>.value(<_i8.Country>[]),
      ) as _i3.Future<List<_i8.Country>>);

  @override
  _i3.Future<_i8.Country?> getCountryById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCountryById,
          [id],
        ),
        returnValue: _i3.Future<_i8.Country?>.value(),
        returnValueForMissingStub: _i3.Future<_i8.Country?>.value(),
      ) as _i3.Future<_i8.Country?>);

  @override
  _i3.Future<void> unlockCountry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #unlockCountry,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i9.LocationRepository {
  @override
  _i3.Future<List<_i10.Location>> getAllLocations() => (super.noSuchMethod(
        Invocation.method(
          #getAllLocations,
          [],
        ),
        returnValue: _i3.Future<List<_i10.Location>>.value(<_i10.Location>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i10.Location>>.value(<_i10.Location>[]),
      ) as _i3.Future<List<_i10.Location>>);

  @override
  _i3.Future<List<_i10.Location>> getLocationsByEra(String? eraId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationsByEra,
          [eraId],
        ),
        returnValue: _i3.Future<List<_i10.Location>>.value(<_i10.Location>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i10.Location>>.value(<_i10.Location>[]),
      ) as _i3.Future<List<_i10.Location>>);

  @override
  _i3.Future<_i10.Location?> getLocationById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getLocationById,
          [id],
        ),
        returnValue: _i3.Future<_i10.Location?>.value(),
        returnValueForMissingStub: _i3.Future<_i10.Location?>.value(),
      ) as _i3.Future<_i10.Location?>);
}
