// Mocks generated by Mockito 5.4.4 from annotations
// in time_walker/test/unit/presentation/providers/user_progress_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:time_walker/domain/entities/dialogue.dart' as _i7;
import 'package:time_walker/domain/entities/era.dart' as _i6;
import 'package:time_walker/domain/entities/user_progress.dart' as _i4;
import 'package:time_walker/domain/repositories/user_progress_repository.dart'
    as _i2;
import 'package:time_walker/domain/services/progression_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProgressRepository extends _i1.Mock
    implements _i2.UserProgressRepository {
  @override
  _i3.Future<_i4.UserProgress?> getUserProgress(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProgress,
          [userId],
        ),
        returnValue: _i3.Future<_i4.UserProgress?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.UserProgress?>.value(),
      ) as _i3.Future<_i4.UserProgress?>);

  @override
  _i3.Future<void> saveUserProgress(_i4.UserProgress? progress) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProgress,
          [progress],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ProgressionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressionService extends _i1.Mock
    implements _i5.ProgressionService {
  @override
  List<_i5.UnlockEvent> checkUnlocks(
    _i4.UserProgress? currentProgress, {
    List<_i6.Era>? allEras,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkUnlocks,
          [currentProgress],
          {#allEras: allEras},
        ),
        returnValue: <_i5.UnlockEvent>[],
        returnValueForMissingStub: <_i5.UnlockEvent>[],
      ) as List<_i5.UnlockEvent>);

  @override
  double calculateEraProgress(
    String? eraId,
    _i4.UserProgress? progress,
    List<_i7.Dialogue>? eraDialogues,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateEraProgress,
          [
            eraId,
            progress,
            eraDialogues,
          ],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  double calculateRegionProgress(
    String? regionId,
    _i4.UserProgress? progress,
    List<_i6.Era>? regionEras,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRegionProgress,
          [
            regionId,
            progress,
            regionEras,
          ],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);
}
